#!/usr/bin/env node

/**
 * Build script that pre-generates the HTML string for the Cloudflare Worker.
 *
 * It reads the MCP Apps SDK browser bundle and pako deflate from node_modules,
 * processes them (strip ESM exports, create App alias), and writes the final
 * HTML as an exported string to src/generated-html.js.
 *
 * Usage: node src/build-html.js
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildHtml, processAppBundle } from "./shared.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read and process app-with-deps.js
const extAppsEntry = fileURLToPath(import.meta.resolve("@modelcontextprotocol/ext-apps/app-with-deps"));
const appWithDepsRaw = fs.readFileSync(extAppsEntry, "utf-8");
const appWithDepsJs = processAppBundle(appWithDepsRaw);

// Read pako deflate
const pakoEntry = fileURLToPath(import.meta.resolve("pako"));
const pakoDeflateJs = fs.readFileSync(
  path.join(path.dirname(pakoEntry), "..", "dist", "pako_deflate.min.js"),
  "utf-8"
);

// Read the drawio-elk bundle (vendored from drawio-dev — see
// vendor/elk/README.md). Defines `var ELK` consumed by drawio-mermaid and
// mxElkLayout. MUST be loaded before drawio-mermaid.
const elkBundlePath = path.join(__dirname, "..", "vendor", "elk", "drawio-elk.min.js");
const elkJs = fs.readFileSync(elkBundlePath, "utf-8");
console.log(`ELK bundle: ${elkBundlePath} (${(elkJs.length / 1024).toFixed(1)} KB)`);

// Read the drawio-mermaid IIFE bundle (vendored from drawio-dev — see
// vendor/mermaid/README.md). Reads globalThis.ELK on init.
const mermaidBundlePath = path.join(__dirname, "..", "vendor", "mermaid", "drawio-mermaid.min.js");
const mermaidJs = fs.readFileSync(mermaidBundlePath, "utf-8");
console.log(`Mermaid bundle: ${mermaidBundlePath} (${(mermaidJs.length / 1024).toFixed(1)} KB)`);

// Read the mxElkLayout wrapper (vendored from drawio-dev origin/elk-layout —
// see vendor/elk/README.md).
const mxElkLayoutPath = path.join(__dirname, "..", "vendor", "elk", "mxElkLayout.js");
const mxElkLayoutJs = fs.readFileSync(mxElkLayoutPath, "utf-8");
console.log(`mxElkLayout: ${mxElkLayoutPath} (${(mxElkLayoutJs.length / 1024).toFixed(1)} KB)`);

// Read the shared XML reference (single source of truth for all prompts)
const xmlReference = fs.readFileSync(
  path.join(__dirname, "..", "..", "shared", "xml-reference.md"),
  "utf-8"
);

// Read the shared Mermaid reference (appended to the create_diagram
// tool description so LLMs get concrete per-type syntax hints).
const mermaidReference = fs.readFileSync(
  path.join(__dirname, "..", "..", "shared", "mermaid-reference.md"),
  "utf-8"
);

// Read the shape search index (optional — skip if not yet generated)
const shapeIndexPath = path.join(__dirname, "..", "..", "shape-search", "search-index.json");
let shapeIndex = null;

if (fs.existsSync(shapeIndexPath))
{
  shapeIndex = JSON.parse(fs.readFileSync(shapeIndexPath, "utf-8"));
  console.log(`Shape index: ${shapeIndex.length} shapes from ${shapeIndexPath}`);
}
else
{
  console.log("Shape index not found at " + shapeIndexPath + " — search_shapes tool will be disabled");
}

// Read the favicon
const faviconPath = path.join(__dirname, "..", "favicon.png");
const faviconBase64 = fs.readFileSync(faviconPath).toString("base64");
console.log(`Favicon: ${faviconPath} (${(faviconBase64.length / 1024).toFixed(1)} KB base64)`);

// Build the HTML and write it as an ES module export
const html = buildHtml(appWithDepsJs, pakoDeflateJs, mermaidJs, { elkJs, mxElkLayoutJs });
const outPath = path.join(__dirname, "generated-html.js");

fs.writeFileSync(outPath,
  `// Auto-generated by build-html.js — do not edit\n` +
  `export const html = ${JSON.stringify(html)};\n` +
  `export const xmlReference = ${JSON.stringify(xmlReference)};\n` +
  `export const mermaidReference = ${JSON.stringify(mermaidReference)};\n` +
  `export const shapeIndex = ${shapeIndex ? JSON.stringify(shapeIndex) : "null"};\n` +
  `export const faviconBase64 = ${JSON.stringify(faviconBase64)};\n`
);

console.log(`Generated ${outPath} (${(html.length / 1024).toFixed(1)} KB HTML` +
  (shapeIndex ? `, ${shapeIndex.length} shapes` : "") + ")");
